cursor #f6dcdf
cursor_text_color #e0bec3

foreground            #f6dcdf
background            #1c1012
selection_foreground  #5b1729
selection_background  #ffb2be
url_color             #ffb2be

color0   #1c1012
color1   #ff7275
color2   #9dff7f
color3   #ffe272
color4   #f29aa8
color5   #76343e
color6   #ffb2be
color7   #ffeff2
color8   #a5999b
color9   #ff9fa1
color10  #baffa5
color11  #ffeda5
color12  #ffbdc7
color13  #ffc9d1
color14  #ffdce1
color15  #fff8f9
