cursor #e3e1ec
cursor_text_color #c5c5d6

foreground            #e3e1ec
background            #12131a
selection_foreground  #252d57
selection_background  #bcc4f7
url_color             #b9c3ff

color0   #12131a
color1   #ff7296
color2   #7fff94
color3   #ffd772
color4   #a2adf2
color5   #3a4376
color6   #b9c3ff
color7   #eff1ff
color8   #999ba5
color9   #ff9fb7
color10  #a5ffb4
color11  #ffe6a5
color12  #c3cbff
color13  #ced4ff
color14  #dfe3ff
color15  #f8f9ff
